// Generated by `arklight pwa` -- do not edit by hand. Re-run
// `arklight pwa <build-dir>` after your next `arklight build`
// instead; this file (including CACHE_NAME) is fully
// regenerated every time, not patched in place.
const CACHE_NAME = "arklight-pwa-6ede68bee7a20d51";
const PRECACHE_URLS = [
  "arklight.js",
  "assets/.gitkeep",
  "index.html",
  "manifest.json",
  "sbom.txt",
  "styles.css"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(
        names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name))
      )
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  event.respondWith(
    caches.match(event.request).then((cached) => cached || fetch(event.request))
  );
});
